# -*- coding: utf-8 -*-
"""Python Scripts.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13vo83Ep89u7B6nuOPgKL6H9ZF6MLVgbx
"""

# Function to convert minutes into hours and minutes
def convert_minutes(minutes):
    hours = minutes // 60
    mins = minutes % 60

    # Build human-readable string
    parts = []
    if hours > 0:
        parts.append(f"{hours} hr{'s' if hours > 1 else ''}")
    if mins > 0:
        parts.append(f"{mins} minute{'s' if mins > 1 else ''}")
    return " ".join(parts)

# Test cases
test_values = [130, 110, 60, 45, 0]

for mins in test_values:
    print(f"{mins} minutes -> {convert_minutes(mins)}")

# Input string
input_str = "programming"

# Empty string to store unique characters
unique_str = ""

# Loop through each character in the input
for char in input_str:
    if char not in unique_str:
        unique_str += char

print("Original string:", input_str)
print("Unique string:", unique_str)